// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtA5DTiuCD21-OUZ7XW8gkQSpNx2vYA0',
    appId: '1:654275178642:web:a0258779715eee3435f64b',
    messagingSenderId: '654275178642',
    projectId: 'team4-8e751',
    authDomain: 'team4-8e751.firebaseapp.com',
    storageBucket: 'team4-8e751.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5aMR7Vnc5toNh__L83zRwqJaT1iFriI',
    appId: '1:654275178642:android:4deb9c94b04af7e935f64b',
    messagingSenderId: '654275178642',
    projectId: 'team4-8e751',
    storageBucket: 'team4-8e751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl686siClRPu5HFMu3WP29H2YkHJraNPs',
    appId: '1:654275178642:ios:95f17989902f03f435f64b',
    messagingSenderId: '654275178642',
    projectId: 'team4-8e751',
    storageBucket: 'team4-8e751.firebasestorage.app',
    iosBundleId: 'com.EcoTrip.ecoTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl686siClRPu5HFMu3WP29H2YkHJraNPs',
    appId: '1:654275178642:ios:95f17989902f03f435f64b',
    messagingSenderId: '654275178642',
    projectId: 'team4-8e751',
    storageBucket: 'team4-8e751.firebasestorage.app',
    iosBundleId: 'com.EcoTrip.ecoTrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjtA5DTiuCD21-OUZ7XW8gkQSpNx2vYA0',
    appId: '1:654275178642:web:9934d612bf950c7535f64b',
    messagingSenderId: '654275178642',
    projectId: 'team4-8e751',
    authDomain: 'team4-8e751.firebaseapp.com',
    storageBucket: 'team4-8e751.firebasestorage.app',
  );
}
